client:
    url:
        ibge: https://servicodados.ibge.gov.br/api/v1/localidades
jwt:
    security:
        token:
            secret: ${JWT_SECRET:9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9}
    token:
        expiration:
            seconds: 1800
server:
    error:
        include-stacktrace: never
spring:
    application:
        name: users
    data:
        mongodb:
            database: test
            host: localhost
            port: 27017
    mvc:
        problemdetails:
            enabled: true
springdoc:
    api-docs:
        path: /api-docs
