client:
    url:
        ibge: https://servicodados.ibge.gov.br/api/v1/localidades
jwt:
    security:
        token:
            secret: ${JWT_SECRET:123456}
    token:
        expiration:
            seconds: 1800
server:
    error:
        include-stacktrace: never
spring:
    application:
        name: users
    data:
        mongodb:
            database: test
            host: localhost
            port: 27017
    mvc:
        problemdetails:
            enabled: true
springdoc:
    api-docs:
        path: /api-docs
